spring.application.name=rdstore
spring.datasource.url=jdbc:mysql://localhost:3307/dstore?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=REMOVED_SECRET

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Opcional. Puedes quitarlo si Spring/Hibernate detecta bien MySQL.
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
